const accent = "#FF6B35";
const accentLight = "#FF8A5C";
const green = "#22C55E";
const blue = "#3B82F6";
const purple = "#8B5CF6";

export default {
  light: {
    text: "#1E1E1E",
    textSecondary: "#8E8E93",
    textTertiary: "#AEAEB2",
    background: "#FAFAFA",
    backgroundSecondary: "#FFFFFF",
    backgroundTertiary: "#F2F2F7",
    card: "#FFFFFF",
    border: "#E5E5EA",
    borderLight: "#F2F2F7",
    tint: accent,
    tintLight: accentLight,
    tabIconDefault: "#C7C7CC",
    tabIconSelected: accent,
    success: green,
    info: blue,
    purple: purple,
    protein: "#5B9FF3",
    carbs: "#FFBF47",
    fat: "#FF6B6B",
    calories: accent,
    shadow: "#000000",
    cardShadow: "rgba(0,0,0,0.04)",
  },
  dark: {
    text: "#F5F5F7",
    textSecondary: "#98989F",
    textTertiary: "#636366",
    background: "#000000",
    backgroundSecondary: "#1C1C1E",
    backgroundTertiary: "#2C2C2E",
    card: "#1C1C1E",
    border: "#38383A",
    borderLight: "#2C2C2E",
    tint: accent,
    tintLight: accentLight,
    tabIconDefault: "#636366",
    tabIconSelected: accent,
    success: green,
    info: blue,
    purple: purple,
    protein: "#64B5F6",
    carbs: "#FFD54F",
    fat: "#EF5350",
    calories: accent,
    shadow: "#000000",
    cardShadow: "rgba(0,0,0,0.3)",
  },
};
