const accent = "#FF6B35";
const accentLight = "#FF8A5C";
const green = "#22C55E";
const blue = "#3B82F6";
const purple = "#8B5CF6";

export default {
  light: {
    text: "#1A1A2E",
    textSecondary: "#6B7280",
    textTertiary: "#9CA3AF",
    background: "#FFFFFF",
    backgroundSecondary: "#F9FAFB",
    backgroundTertiary: "#F3F4F6",
    card: "#FFFFFF",
    border: "#F0F0F0",
    borderLight: "#F5F5F5",
    tint: accent,
    tintLight: accentLight,
    tabIconDefault: "#B0B0B0",
    tabIconSelected: accent,
    success: green,
    info: blue,
    purple: purple,
    protein: "#3B82F6",
    carbs: "#F59E0B",
    fat: "#EF4444",
    calories: accent,
    shadow: "#000000",
    cardShadow: "rgba(0,0,0,0.04)",
  },
  dark: {
    text: "#F9FAFB",
    textSecondary: "#9CA3AF",
    textTertiary: "#6B7280",
    background: "#111827",
    backgroundSecondary: "#1F2937",
    backgroundTertiary: "#1F2937",
    card: "#1F2937",
    border: "#374151",
    borderLight: "#1F2937",
    tint: accent,
    tintLight: accentLight,
    tabIconDefault: "#6B7280",
    tabIconSelected: accent,
    success: green,
    info: blue,
    purple: purple,
    protein: "#60A5FA",
    carbs: "#FBBF24",
    fat: "#F87171",
    calories: accent,
    shadow: "#000000",
    cardShadow: "rgba(0,0,0,0.3)",
  },
};
