import React from "react";
import { View, Text, StyleSheet, ScrollView, Pressable } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";

export default function TermsScreen() {
  const { top } = useSafeAreaInsets();
  const router = useRouter();

  return (
    <View style={[s.container, { paddingTop: top }]}>
      <View style={s.header}>
        <Pressable onPress={() => router.back()} style={s.backBtn}>
          <Ionicons name="chevron-back" size={24} color="#fff" />
        </Pressable>
        <Text style={s.headerTitle}>Terms & Conditions</Text>
        <View style={{ width: 40 }} />
      </View>
      <ScrollView style={s.scroll} contentContainerStyle={s.scrollContent} showsVerticalScrollIndicator={false}>
        <Text style={s.lastUpdated}>Last Updated: March 26, 2026</Text>

        <Text style={s.body}>
          Welcome to CaloriZen™. These Terms and Conditions ("Terms") govern your access to and use of the CaloriZen™ mobile application ("App"), operated by CaloriZen™ ("Company," "we," "us," or "our"). By downloading, installing, or using the App, you agree to be bound by these Terms. If you do not agree, do not use the App.
        </Text>

        <Text style={s.sectionTitle}>1. Acceptance of Terms</Text>
        <Text style={s.body}>
          By creating an account or using CaloriZen™, you confirm that you are at least 13 years of age and have the legal capacity to enter into these Terms. If you are under 18, you must have permission from a parent or legal guardian. Your continued use of the App constitutes acceptance of these Terms and any future modifications.
        </Text>

        <Text style={s.sectionTitle}>2. Description of Service</Text>
        <Text style={s.body}>
          CaloriZen™ is an AI-powered calorie and nutrition tracking application that allows users to:{"\n\n"}
          • Photograph meals for automatic nutritional analysis{"\n"}
          • Scan food barcodes for product information{"\n"}
          • Track daily calorie and macronutrient intake{"\n"}
          • Set personalized nutrition goals{"\n"}
          • View food log history by date{"\n\n"}
          The App uses artificial intelligence, including OpenAI's GPT Vision technology, to estimate nutritional content from photographs. These estimates are approximations and should not be relied upon as medical or dietary advice.
        </Text>

        <Text style={s.sectionTitle}>3. Account Registration</Text>
        <Text style={s.body}>
          To use CaloriZen™, you must create an account using one of our supported authentication providers (Google or Apple Sign-In). You agree to:{"\n\n"}
          • Provide accurate and complete information during registration{"\n"}
          • Maintain the security of your account credentials{"\n"}
          • Notify us immediately of any unauthorized use of your account{"\n"}
          • Accept responsibility for all activities under your account{"\n\n"}
          We reserve the right to suspend or terminate accounts that violate these Terms or engage in fraudulent activity.
        </Text>

        <Text style={s.sectionTitle}>4. Intellectual Property</Text>
        <Text style={s.body}>
          CaloriZen™ and all associated trademarks, logos, designs, text, graphics, and software are the exclusive property of the Company and are protected by intellectual property laws. The CaloriZen™ name and logo are trademarks pending registration. You may not:{"\n\n"}
          • Copy, modify, or distribute any part of the App{"\n"}
          • Reverse engineer or decompile the App's software{"\n"}
          • Use the CaloriZen™ name or branding without written permission{"\n"}
          • Create derivative works based on the App
        </Text>

        <Text style={s.sectionTitle}>5. User Content</Text>
        <Text style={s.body}>
          You retain ownership of photographs and data you submit through the App ("User Content"). By submitting User Content, you grant CaloriZen™ a non-exclusive, worldwide, royalty-free license to use, process, and analyze your content solely for the purpose of providing and improving our services. We will not sell, share, or publicly display your food photographs or personal nutrition data without your explicit consent.
        </Text>

        <Text style={s.sectionTitle}>6. AI-Powered Analysis Disclaimer</Text>
        <Text style={s.body}>
          The nutritional estimates provided by CaloriZen™ are generated by artificial intelligence and are approximations only. Results may vary based on image quality, food preparation methods, portion sizes, and other factors. CaloriZen™ does not guarantee the accuracy of any nutritional analysis.{"\n\n"}
          The App is not a substitute for professional medical, dietary, or nutritional advice. Always consult a qualified healthcare professional before making dietary changes, especially if you have allergies, medical conditions, or specific dietary requirements.
        </Text>

        <Text style={s.sectionTitle}>7. Prohibited Uses</Text>
        <Text style={s.body}>
          You agree not to:{"\n\n"}
          • Use the App for any unlawful purpose{"\n"}
          • Attempt to gain unauthorized access to our systems or servers{"\n"}
          • Upload malicious content, viruses, or harmful code{"\n"}
          • Interfere with the App's functionality or other users' experience{"\n"}
          • Use automated tools to scrape or extract data from the App{"\n"}
          • Impersonate another person or entity{"\n"}
          • Resell or commercially exploit the App without authorization
        </Text>

        <Text style={s.sectionTitle}>8. Subscription & Payments</Text>
        <Text style={s.body}>
          CaloriZen™ may offer free and premium subscription tiers. If you purchase a subscription:{"\n\n"}
          • Payment will be charged to your Apple ID or Google Play account{"\n"}
          • Subscriptions automatically renew unless canceled at least 24 hours before the end of the current period{"\n"}
          • You can manage or cancel subscriptions through your device's app store settings{"\n"}
          • Refunds are subject to the policies of Apple App Store or Google Play Store
        </Text>

        <Text style={s.sectionTitle}>9. Limitation of Liability</Text>
        <Text style={s.body}>
          To the maximum extent permitted by applicable law, CaloriZen™ and its officers, directors, employees, and agents shall not be liable for:{"\n\n"}
          • Any indirect, incidental, special, consequential, or punitive damages{"\n"}
          • Loss of data, revenue, or profits{"\n"}
          • Health issues arising from reliance on AI-generated nutritional estimates{"\n"}
          • Service interruptions, errors, or inaccuracies{"\n\n"}
          Our total liability shall not exceed the amount you have paid to CaloriZen™ in the twelve (12) months preceding the claim.
        </Text>

        <Text style={s.sectionTitle}>10. Indemnification</Text>
        <Text style={s.body}>
          You agree to indemnify and hold harmless CaloriZen™, its affiliates, and their respective officers, directors, employees, and agents from any claims, damages, losses, liabilities, costs, and expenses (including attorney's fees) arising from your use of the App, violation of these Terms, or infringement of any third-party rights.
        </Text>

        <Text style={s.sectionTitle}>11. Third-Party Services</Text>
        <Text style={s.body}>
          CaloriZen™ integrates with third-party services including but not limited to Google Sign-In, Apple Sign-In, and OpenAI. Your use of these services is subject to their respective terms and privacy policies. We are not responsible for the practices or availability of third-party services.
        </Text>

        <Text style={s.sectionTitle}>12. Modifications to Terms</Text>
        <Text style={s.body}>
          We reserve the right to modify these Terms at any time. Changes will be effective upon posting within the App. Your continued use after changes are posted constitutes acceptance of the revised Terms. We will make reasonable efforts to notify users of material changes through in-app notifications.
        </Text>

        <Text style={s.sectionTitle}>13. Termination</Text>
        <Text style={s.body}>
          We may suspend or terminate your access to the App at any time, with or without cause, and with or without notice. Upon termination, your right to use the App ceases immediately. Sections regarding intellectual property, limitation of liability, and indemnification survive termination.
        </Text>

        <Text style={s.sectionTitle}>14. Governing Law</Text>
        <Text style={s.body}>
          These Terms shall be governed by and construed in accordance with the laws of the United States, without regard to conflict of law provisions. Any disputes arising from these Terms or your use of the App shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association.
        </Text>

        <Text style={s.sectionTitle}>15. Contact Information</Text>
        <Text style={s.body}>
          If you have questions or concerns about these Terms, please contact us at:{"\n\n"}
          CaloriZen™{"\n"}
          Email: legal@calorizen.ai{"\n"}
          Website: https://calorizen.ai
        </Text>

        <Text style={[s.body, { marginTop: 24, fontFamily: "Inter_600SemiBold" }]}>
          By using CaloriZen™, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions.
        </Text>

        <View style={{ height: 60 }} />
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0F0F0F" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.08)",
  },
  backBtn: { width: 40, height: 40, alignItems: "center", justifyContent: "center" },
  headerTitle: { fontSize: 17, fontFamily: "Inter_600SemiBold", color: "#fff" },
  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: 24, paddingTop: 24 },
  lastUpdated: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    color: "rgba(255,255,255,0.4)",
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 17,
    fontFamily: "Inter_700Bold",
    color: "#fff",
    marginTop: 28,
    marginBottom: 10,
  },
  body: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    color: "rgba(255,255,255,0.7)",
    lineHeight: 22,
    marginBottom: 8,
  },
});
